# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import docx_py_pb2 as docx__py__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in docx_py_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocxPyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateDocument = channel.unary_unary(
                '/DocxPy/GenerateDocument',
                request_serializer=docx__py__pb2.DocumentRequest.SerializeToString,
                response_deserializer=docx__py__pb2.DocumentResponse.FromString,
                _registered_method=True)


class DocxPyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocxPyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDocument,
                    request_deserializer=docx__py__pb2.DocumentRequest.FromString,
                    response_serializer=docx__py__pb2.DocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DocxPy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DocxPy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocxPy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DocxPy/GenerateDocument',
            docx__py__pb2.DocumentRequest.SerializeToString,
            docx__py__pb2.DocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
